[package]
name = "gitea-update-checker"
version = "0.1.3"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]

[dependencies]
clap = "2.33.0"
rayon = "1.2.0"
failure = "0.1.6"
reqwest = "0.9.20"
semver = "0.9.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
